### ISSUE TITLE
Payer phone number validation has confusing field name and rule

### ISSUE THREAD

**Issue by bruny** [darcys22/empdupe#2]
When entering a mobile phone number for payer information, the field commonly autofills (since the browser recognises it as a common form field) with a standard "04xx 000 000" format.

Validating the payer then results in the following error:
```
number:
0:Number can only contain 0-9
```

This is slightly confusing since the form has "Contact number", so it's not obvious which field its complaining about.

Also, the ABN allows spaces in it, so contact number should as well (code can always remove any spaces/special characters).

**Comment by darcys22** [comment]
Yep, 
Should be trivial to add the whitespace trim to the phone number field

**Comment by bruny** [comment]
I don't have much familiarity with js but let me have a look and see if I can get a reasonable PR. I'll change the field from number to contactNumber as well.

**Comment by darcys22** [comment]
https://github.com/darcys22/empdupe/commit/538073084153e58b983f5d68953897ce4ac38f67
