### ISSUE TITLE
PDF generation fails silently when jsPDF doesn't exist

### ISSUE THREAD

**Issue by bruny** [darcys22/empdupe#3]
empdupe.txt is created successfully, but PDF generation fails silently if client doesn't have (presumably) jspdf library installed.

Note this is when the repo is forked and index.html is opened on local computer rather than the empdupe.com site.

**Comment by bruny** [comment]
```
$ npm list
/Users/bruny/Documents/projects/empdupe
└─┬ jspdf@1.3.3
  ├── adler32cs@0.0.1 (git://github.com/chick307/adler32cs.js.git#c6576b4ed91b4216973bf85d8478a49970934515)
  ├── cf-blob.js@0.0.1
  └── filesaver.js@1.0.0 (git://github.com/andyinabox/FileSaver.js.git#973b433b8fbaee9a11d53b9ae423b046742cfe32)


```

**Comment by darcys22** [comment]
Does it fail silently? I imagine the console would have a jspdf not found error

**Comment by darcys22** [comment]
Although I recommend running a some form of web server to serve the html. When I run the index page on its own it still fetches the CDN of jspdf.

Try it with
`python -m SimpleHTTPServer`

**Comment by bruny** [comment]
Yep, the error was actually being recorded in Chrome console:

```
jspdf.min.js:27 Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at g (https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.min.js:27:3089)
    at Object.e.addImage (https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.min.js:27:6514)
    at Image.background.onload (file:///Users/bruny/Documents/projects/empdupe/js/main.js:1006:18)
```

So looks like a CORS issue, mainly due to Chrome security issues when opening the index.html using the file browser.

As per your suggestion, running python -m SimpleHTTPServer in the directory empdupe is in, and using http://0.0.0.0:8000 serves it correctly.
